### ISSUE TITLE
Feature Request: Add noise and masking information to FITS headers

### ISSUE THREAD

**Issue by jmangum** [keflavich/cube-line-extractor#10]
Since the RMS noise and masking parameters used to derive the moment maps from CubeLineMoment are often useful to know when using these measurements in an analysis of their results, I wonder if it would be useful to add this information to the moment FITS headers?

**Comment by keflavich** [comment]
Sure, that's easy to do.  Just add header parameters with `header['MASKLEV'] = mask_level` or something along those lines.

**Comment by jmangum** [comment]
ok.  Let me try to take this one on.

**Comment by jmangum** [comment]
Should these be added as header keywords or comment or history entries?

**Comment by keflavich** [comment]
Either way is fine; keywords are easier to access later.  You can do thinks like:
`header['MASKLEV'] = (mask_level, 'Threshold in Jy used to create the mask cube')`
if you want a `/ comment` added to the header entry

**Comment by jmangum** [comment]
ok.  Will use `header`.
