### ISSUE TITLE
Feature Request: Better Description of How to Use Script

### ISSUE THREAD

**Issue by jmangum** [keflavich/cube-line-extractor#15]
Really just an update to the current documentation.  For example, need to explain that one needs to set sample_pixel in order to get diagnostic plots.

**Comment by jmangum** [comment]
Should also note that choice of sample pixel is very important.  Best to choose one of the strongest peaks.

**Comment by keflavich** [comment]
:+1:
@kakirastern you have any interest in tackling this bit of documentation?

**Comment by kakirastern** [comment]
@keflavich Sure

**Comment by kakirastern** [comment]
Will need to test drive the code before completing this task. Will take at least a couple of days.

**Comment by jmangum** [comment]
Can this issue be closed?

**Comment by keflavich** [comment]
Closed by #23
