### ISSUE TITLE
Feature Request: Allow for Multiple Sample Pixels

### ISSUE THREAD

**Issue by jmangum** [keflavich/cube-line-extractor#18]
Since a single sample_pixel might not be enough, might be useful to allow for the extraction of multiple pixels.  Perhaps done by reading a ds9 regions file.

**Comment by jmangum** [comment]
Revisiting this feature request.  The origin for the `sample_pixel` implementation was, if I recall, to give us a way to produce some diagnostic plots (spectra) which could be used to determine if the input parameters for the moment extractions (`noisemapbright_baseline`, `noisemap_baseline`, `velocity_half_range`, `my_line_widths`) are reasonable.  For example, I normally use the diagnostic plots to tweak `my_line_widths`.  Having just one `sample_pixel` seems a bit dangerous, as one wants to set the moment extraction parameters to be reasonable toward all positions in the target cube.  Multiple `sample_pixel` values might help, but still seems non-optimal.  Would it make sense to generate an average spectrum over an input region that might encompass anywhere from a few beam widths in size to the entire emission region in an image (for ALCHEMI, this might be the entire CMZ)?

**Comment by keflavich** [comment]
Multiple sample pixels is easy enough to loop over.

An average spectrum is also not too hard, but is awkward as part of the point of this tool is that there are velocity gradients, and averaging over them smears one feature into another.  It's doable, of course, but is it really worth it?

**Comment by jmangum** [comment]
Thanks.  I guess then the multiple sample pixels should produce multiple diagnostic plots?  Also, we currently just cut a spectrum through a single pixel.  Would it be better to take the mean over a beam-sized area centered on each of the 'sample_pixel` positions?

**Comment by keflavich** [comment]
Yes, multiple plots is the way to do this.  We could do a grid of plots, but that could get painful fast.

In principle, averaging over a beam-sized area and selecting a single pixel should have little difference - just ~sqrt(2) blurring.  Right?

**Comment by jmangum** [comment]
You are right.  Since we don't really care about the quality of the intensities plotted (no science done with these diagnostic plots), then averaging over a beam is not necessary.

**Comment by keflavich** [comment]
ok so the strategy is basically: 
* accept `sample_pixels` as a keyword
* check if there are multiple sample pixels (as opposed to one) - remember that `sample_pixel` is a pair
* for loop over the sample pixels, saving each figure as, e.g., `diagnostics/samplepixel{sample_pixel[0]}-{sample_pixel[1]}....png`
