### ISSUE TITLE
Clean-up Testing Calculations of Line Width, FWHM, Variance, and Centroid

### ISSUE THREAD

**Issue by jmangum** [keflavich/cube-line-extractor#26]
Remnant from original development of this application.  We calculate width_map, fwhm_map, sqrtmom2_map, and centroid_map but only use width_map and centroid_map for various kinds of masking.  Before removing the unused fwhm_map and sqrtmom2_map calculations, wondering which of these width-related images:

(1) width_map
(2) fwhm_map
(3) sqrtmom2_map

...is the *right* one to use for width masking?

**Comment by keflavich** [comment]
they're all equivalent.  sqrtmom2=width=fwhm/2.35

**Comment by jmangum** [comment]
ok.  Suggest removing `fwhm_map` and `sqrtmom2_map` then and sticking with using `width_map` for masking.

**Comment by keflavich** [comment]
could you submit a PR doing that?

**Comment by jmangum** [comment]
Yes.  I am working from a branch at the moment that I thought would address several of these minor "cleanup" issues.

**Comment by jmangum** [comment]
Resolved with PR #28
