### ISSUE TITLE
Use of std on masked noisecubebright cube produces warning

### ISSUE THREAD

**Issue by jmangum** [keflavich/cube-line-extractor#37]
The following line:
```
noisemapbright = noisecubebright.with_mask(mask[:,None,None]).std(axis=0)
```
...produces the following warning...
```
/Users/jmangum/anaconda3/envs/python39/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1878: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
```
Probably innocuous, but would like to fix if I knew what was causing this warning.

**Comment by keflavich** [comment]
That implies that there is at least one spectrum that consists of only 1 pixel, so the standard deviation can't be computed.  i.e., `noisemask.with_mask(mask[:,None,None]).include().sum(axis=0)` will have at least one pixel with value 1

**Comment by jmangum** [comment]
ok.  Looks innocuous.  Should we just educate users about this warning in the documentation?

**Comment by keflavich** [comment]
yeah.  We can also probably find a way to silence it... though I'm not immediately sure how as this isn't one of the `seterr`-ignorable warnings.
