### ISSUE TITLE
Feature Request: Loop over mask limits read from yaml file

### ISSUE THREAD

**Issue by jmangum** [keflavich/cube-line-extractor#5]
It would be convenient to be able to generate a range of signal_mask_limit and spatial_mask_limit valued moment maps in order to sample a range in each of these parameters.  Currently CubeLineMoment just runs cubelinemoment_multiline several times with different values for width_map_scaling, width_cut_scaling, and signal_mask_limit.  Would be better to put this in a loop.

**Comment by keflavich** [comment]
So to clarify, you want multiple MomentX maps made with different values of each of those parameters?

**Comment by jmangum** [comment]
I think that which parameters are worth iterating is an open question.  We have the following:
(1) signal_mask_limit (input from yaml)
(2) spatial_mask_limit (input from yaml)
(3) width_map_scaling
(4) width_cut_scaling

Now, (1) and (2) are N*RMS values, and I always find it tricky to figure out where to set a cutoff.  Seems often to be the case that a reasonable value lies somewhere between 2 and 3, so one might want to produce moment maps using values of 2.0, 2.5, and 3.0, for example.

The other two parameters (numbers 3 and 4 in the list above) are less clear.  One might like to iterate on these also, but then you get into a situation where you are produce a lot of moment maps.

Suggest that we put this one on a low priority for now until we get more experience with which parameters require more investigation for a given data set.  The current solution where cubelinemoment_multiline is run several times work fine.

**Comment by jmangum** [comment]
After 5+ years of use I no longer see a need for this feature.  Closing.
