### ISSUE TITLE
Feature Request: Use "Brightest Line" Cube Which Does Not Share Image Cube Parameters of Target Cube

### ISSUE THREAD

**Issue by jmangum** [keflavich/cube-line-extractor#6]
It is often the case that the "brightest line" for the CubeLineMoment calculations is not usually from the same spw as the target lines to be extracted from the cube.  This means that the brightest line is not necessarily sampled on the same spatial grid (i.e. might not have the same beam characteristics) as the target lines).  It would make more sense to be able to use a "brightest line" cube from any instrument with sufficient spatial and spectral resolution (so as to be sampling the same structure as the target line measurements).  Using our Band 6 and 7 ALMA data as an example, it would be convenient to be able to use the C18O 2-1 transition as the brightest line for all Band 6 and 7 measurements processed.  Note that this will (often) require interpolation of brightest line cube to the same grid, beam, and velocity scaling as the target line cube.

**Comment by keflavich** [comment]
This is possible and probably straightforward.  I don't think we should automate it too much, at least at first.

**Comment by jmangum** [comment]
Agreed.

**Comment by jmangum** [comment]
I am working on implementing this feature and think there is an inconsistency in the current assignment of the `noisecube` in `CubeLineMoment`.  We currently assign `noisecube` to be equal to `cutoutcube`:
```
noisecube = cutoutcube
```
Recall that each of these cubes is defined as follows:
```
    cube : str
        The cube file name
    cuberegion : str, optional
        A ds9 region file specifying a spatial region to extract from the cube
    cutoutcube : str
        Filename of a cube that specifies the PPV region over which the moments
        will be extracted.
    cutoutcuberegion : str, optional
        A ds9 region file specifying a spatial region to extract from the
        spatial mask cube.  Should generally be the same as cuberegion.
        NOTE TO JEFF: should this *always* be the same as cuberegion?
```
I am testing this by finding moments for the HCN 1-0 transition (88.6 GHz) using a 13CO 2-1 (220.4 GHz) image cube, both from ALCHEMI.  Shouldn't `noisecube = cube`?

**Comment by keflavich** [comment]
if there are better names to use, please go ahead and substitute them in - good variable names are better than comments, since comments can grow stale as code changes.  I'll review changes if you put them in a PR

**Comment by jmangum** [comment]
ok.  I am reluctant to try to make wholesale variable name changes as I have run myself in circles trying to do that in the past with other scripts.  Perhaps in this case replace 'noisecube` with 'noisecubebright`?
